name = "JuMPObjectiveUtils"
uuid = "0f1822af-9829-4456-85d8-f59d17f18c74"
authors = ["lassepe <lasse.peters@mailbox.org>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1.5"
